sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.9.1-0~trusty

before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - docker version

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .

script:
  nosetests --with-coverage --cover-package=docker-master

after_success:
  coveralls